import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Grid } from '@mui/material';
import I3Form from '@/components/i3Form';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>3i Program App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="My page title" key="title" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Image
            className={styles.logo}
            // src="/next.svg"
            src="/siemens-logo-dark-3958fff2.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <Grid container display={'flex'} justifyContent="center">
          <Grid item>
            <I3Form />
          </Grid>
        </Grid>

        <div className={styles.center}>
          <div className={styles.description}>
            <p>
              Nueva Idea de Mejora?&nbsp;
              {/* <code className={styles.code}>pages/index.tsx</code> */}
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
